# Generated by Django 4.0.3 on 2023-04-24 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0002_alter_customer_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='price',
            field=models.PositiveSmallIntegerField(default=10000),
            preserve_default=False,
        ),
    ]
