# Generated by Django 4.0.3 on 2023-04-25 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0002_alter_status_id_alter_status_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='status',
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
