# Generated by Django 4.0.3 on 2023-06-10 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0005_alter_appointment_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Status',
        ),
    ]
